version: "3"
services:
  web:
    image: paprikalang/python-demo:0.1.0
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4100:80"
    networks:
      - webnet
networks:
  webnet: